image: maven:3.6.3-jdk-11  # Use an image with Maven and JDK installed

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository  # Cache Maven repository to speed up builds

build_job:
  stage: build
  script:
    - mvn compile  # Compile the project
  artifacts:
    paths:
      - target/  # Store the compiled artifacts for other stages or jobs

test_job:
  stage: test
  script:
    - mvn test  # Run tests
