image: maven:3.8.4-openjdk22

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository 
build_job:
  stage: build
  script:
    - mvn compile  
  artifacts:
    paths:
      - target/

test_job:
  stage: test
  script:
    - mvn test
